version: '3'

services:
  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  amigo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  emprestimo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  game.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

